# Generated by Django 4.2.16 on 2024-10-14 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogapp', '0002_dog_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=20)),
                ('friendliness', models.IntegerField()),
                ('trainability', models.IntegerField()),
                ('sheddingamount', models.IntegerField()),
                ('exerciseneeds', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='color',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='dog',
            name='favoritefood',
            field=models.CharField(default='Kibble', max_length=255),
        ),
        migrations.AddField(
            model_name='dog',
            name='favoritetoy',
            field=models.CharField(default='Ball', max_length=255),
        ),
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogapp.breed'),
        ),
    ]
